# Generated by Django 5.2.11 on 2026-02-27 07:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CrawlJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-friendly job name", max_length=255
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "config_json",
                    models.JSONField(
                        default=dict, help_text="Full PipelineConfig as JSON"
                    ),
                ),
                (
                    "seed_urls",
                    models.TextField(help_text="Newline-separated seed URLs"),
                ),
                ("max_pages", models.PositiveIntegerField(default=100)),
                ("max_depth", models.PositiveIntegerField(default=3)),
                (
                    "chunk_strategy",
                    models.CharField(default="recursive", max_length=30),
                ),
                ("chunk_size", models.PositiveIntegerField(default=512)),
                ("export_format", models.CharField(default="jsonl", max_length=20)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("pages_crawled", models.PositiveIntegerField(default=0)),
                ("pages_failed", models.PositiveIntegerField(default=0)),
                ("pages_extracted", models.PositiveIntegerField(default=0)),
                ("total_chunks", models.PositiveIntegerField(default=0)),
                ("total_tokens", models.PositiveBigIntegerField(default=0)),
                (
                    "output_path",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "log_text",
                    models.TextField(
                        blank=True, default="", help_text="Pipeline execution log"
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("progress", models.PositiveSmallIntegerField(default=0)),
                (
                    "current_stage",
                    models.CharField(blank=True, default="", max_length=50),
                ),
            ],
            options={
                "verbose_name": "Crawl Job",
                "verbose_name_plural": "Crawl Jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CrawlJobChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chunk_id", models.CharField(db_index=True, max_length=64)),
                ("document_url", models.URLField(max_length=2000)),
                (
                    "document_title",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("text", models.TextField()),
                ("token_count", models.PositiveIntegerField(default=0)),
                ("chunk_index", models.PositiveIntegerField(default=0)),
                ("total_chunks", models.PositiveIntegerField(default=0)),
                (
                    "content_hash",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("metadata_json", models.JSONField(default=dict)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="dashboard.crawljob",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chunk",
                "ordering": ["document_url", "chunk_index"],
            },
        ),
    ]
